/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import ether.TransactionsManager;
import io.left.rightmesh.mesh.JavaMeshManager;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class SuperPeer {

    //TODO: Add logger instead of system.out
    public static final String TAG = SuperPeer.class.getCanonicalName();

    public static void main(String[] args) {
        SuperPeer p = new SuperPeer();
    }

    public SuperPeer() {
        JavaMeshManager mm = new JavaMeshManager(true);
        System.out.println("Superpeer MeshID: " + mm.getUuid());

        System.out.println("Waiting for lib to be ready");
        try {
            Thread.sleep(200);
        } catch (Exception ex) {
        }

        TransactionsManager tm = TransactionsManager.getInstance(mm);
        tm.start();

        //Continue to run until user quits
        System.out.println("Enter empty line to quit");
        String msg;
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

        do {
            try {
                msg = br.readLine();
            } catch (IOException e) {
                e.printStackTrace();
                break;
            }
        } while (msg != null && !msg.equals(""));

        tm.stop();
        mm.stop();
    }
}
