/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import ether.EtherClient;
import ether.TransactionsManager;
import io.left.rightmesh.id.MeshID;
import io.left.rightmesh.mesh.JavaMeshManager;
import io.left.rightmesh.mesh.MeshManager;
import io.left.rightmesh.mesh.MeshManager.MeshTransactionEvent;
import io.left.rightmesh.util.MeshUtility;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import static io.left.rightmesh.mesh.MeshManager.TRANSACTION_RECEIVED;
 
public class SuperPeer {

    //TODO: Add logger instead of system.out
    public static final String TAG = SuperPeer.class.getCanonicalName();
        
    public static void main(String[] args) {
        SuperPeer p = new SuperPeer();
    }
    
    public SuperPeer() {
        JavaMeshManager mm = new JavaMeshManager(true);
        System.out.println("Superpeer MeshID: " + mm.getUuid());
        
        System.out.println("Waiting for lib to be ready");
        try {
                Thread.sleep(200);
        } catch(Exception ex) {}

        TransactionsManager tm = TransactionsManager.getInstance(mm);
        tm.start();

        //test send on the TRANSACTION PORT
        //mm.sendDataReliable(mm.getUuid(), MeshUtility.TRANSACTION_PORT, "test".getBytes());
        
        //Continue to run until user quits
        System.out.println("Enter empty line to quit");
        String msg = "";
//        Console c = System.console();
//        if (c == null) {
//            System.err.println("No console.");
//            mm.stop();
//            return;
//        }

        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

        do {
            //msg = c.readLine();
            try {
                msg = br.readLine();
            } catch (IOException e) {
                e.printStackTrace();
                break;
            }
        } while(msg != null && !msg.equals(""));

        tm.stop();
        mm.stop();

        
    }
}
