/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import ether.TransactionsManager;

import io.left.rightmesh.id.MeshID;
import io.left.rightmesh.mesh.JavaMeshManager;
import io.left.rightmesh.mesh.MeshStateListener;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;


public class SuperPeer implements MeshStateListener {

    //TODO: Add logger instead of system.out
    public static final String TAG = SuperPeer.class.getCanonicalName();

    private static final String EXIT_CMD = "exit";
    private static final String CLOSE_CHANNEL_CMD = "close";


    private boolean isRunning = true;
    private TransactionsManager tm;

    public static void main(String[] args) {
        SuperPeer p = new SuperPeer();
    }

    public SuperPeer() {
        JavaMeshManager mm = new JavaMeshManager(true);
        System.out.println("Superpeer MeshID: " + mm.getUuid());

        System.out.println("Waiting for lib to be ready");
        try {
            Thread.sleep(200);
        } catch (InterruptedException e) {
        }

        tm = TransactionsManager.getInstance(mm);
        tm.start();

        String msg;
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

        do {
            try {
                msg = br.readLine();
                processInput(msg);
            } catch (IOException e) {
                e.printStackTrace();
                break;
            }
        } while (isRunning);

        tm.stop();
        mm.stop();
    }

    public void meshStateChanged(MeshID meshID, int state) {

        if (state == MeshStateListener.SUCCESS) {
            tm.start();
        }
    }

    private void processInput(String msg) {
        if(msg.equals(EXIT_CMD)) {
            isRunning = false;
            return;
        }

        String[] args = msg.split(" ");
        if(args.length == 0) {
            return;
        }

        switch (args[0]) {
            case CLOSE_CHANNEL_CMD:
                processCloseCmd(args);
                break;

            default:
                System.out.println("Invalid command.");
                break;
        }
    }

    private void processCloseCmd(String[] args) {
        if(args.length != 2) {
            System.out.println("Invalid args.");
            return;
        }

        tm.closeChannels(args[1]);
    }
}
